method: random  # You can also choose grid or bayes
metric:
  name: loss
  goal: minimize
parameters:
  position_lr_init:
    distribution: uniform
    min: 0.00001
    max: 0.001
  position_lr_final:
    distribution: uniform
    min: 0.000001
    max: 0.0001
  feature_lr:
    values: [0.0025, 0.005, 0.0075]
  opacity_lr:
    values: [0.025, 0.05, 0.075]
  lambda_dssim:
    distribution: uniform
    min: 0.1
    max: 0.3